# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Root workspace - manages shared dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group all AWS SDK updates into single PR
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "aws-sdk"
      # Group all testing framework updates
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "jest*"
          - "@jest/*"
      # Group all TypeScript/build tools
      build-tools:
        patterns:
          - "typescript"
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
      # Group all AWS CDK updates
      aws-cdk:
        patterns:
          - "aws-cdk-lib"
          - "@aws-cdk/*"
          - "constructs"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Keep commander at v13.x to maintain Node.js 18 compatibility
      - dependency-name: "commander"
        versions: [">=14.0.0"]

  # Individual packages only if they have unique dependencies
  - package-ecosystem: "npm" 
    directory: "/aws-cdk-examples/eks"
    schedule:
      interval: "weekly"
    groups:
      aws-cdk-eks:
        patterns:
          - "aws-cdk-lib"
          - "@aws-cdk/*"
          - "constructs"
    commit-message:
      prefix: "deps(eks)"
      include: "scope"
