name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18.19.1'
  PNPM_VERSION: '10.14.0'

jobs:
  # Job 1: Install dependencies and cache
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Generate cache keys
        id: cache-keys
        run: |
          echo "cache-key=${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  # Job 2: Lint and format check
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: |
          # Check if root has lint script
          if [ -f "package.json" ] && grep -q '"lint"' package.json; then
            echo "Running root lint script..."
            pnpm lint
          else
            echo "No root lint script found, checking individual packages..."
            # Try linting individual packages
            for dir in aws-cdk-examples/*/; do
              if [ -f "$dir/package.json" ] && grep -q '"lint"' "$dir/package.json"; then
                echo "Linting $dir..."
                cd "$dir" && pnpm lint && cd ../..
              fi
            done
            for dir in aws-sdk-examples/*/; do
              if [ -f "$dir/package.json" ] && grep -q '"lint"' "$dir/package.json"; then
                echo "Linting $dir..."
                cd "$dir" && pnpm lint && cd ../..
              fi
            done
          fi

      - name: Check formatting
        run: |
          if [ -f "package.json" ] && grep -q '"format:check"' package.json; then
            pnpm format:check
          else
            echo "No format:check script found, skipping..."
          fi

  # Job 3: Build all packages
  build:
    name: Build All Packages
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        package:
          - aws-cdk-examples/eks
          - aws-sdk-examples/list-lambdas
          - aws-sdk-examples/list-pods
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: |
          cd ${{ matrix.package }}
          if [ -f "package.json" ] && grep -q '"build"' package.json; then
            pnpm build
          else
            echo "No build script found for ${{ matrix.package }}, skipping..."
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.package }}-${{ github.sha }}
          path: ${{ matrix.package }}/dist
          retention-days: 1

  # Job 4: Test with coverage
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        package:
          - name: list-pods
            path: aws-sdk-examples/list-pods
            filter: "@cloud-projects/list-pods-example"
            coverage-threshold: 70
          - name: list-lambdas
            path: aws-sdk-examples/list-lambdas
            filter: "@cloud-projects/list-lambdas-example" 
            coverage-threshold: 50
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          cd ${{ matrix.package.path }}
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            pnpm test
          else
            echo "No test script found for ${{ matrix.package.name }}, skipping..."
            exit 0
          fi

      - name: Run coverage
        run: |
          cd ${{ matrix.package.path }}
          if [ -f "package.json" ] && grep -q '"test:coverage"' package.json; then
            pnpm test:coverage
          else
            echo "No coverage script found for ${{ matrix.package.name }}, skipping..."
            exit 0
          fi

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          file: ${{ matrix.package.path }}/coverage/lcov.info
          flags: ${{ matrix.package.name }}
          name: ${{ matrix.package.name }}-coverage
          fail_ci_if_error: false

      - name: Coverage comment
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ${{ matrix.package.path }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Report - ${{ matrix.package.name }}

  # Job 5: Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for vulnerabilities
        run: |
          if pnpm audit --audit-level high --json > audit.json 2>/dev/null; then
            echo "No high-severity vulnerabilities found"
          else
            echo "High-severity vulnerabilities detected!"
            cat audit.json
            exit 1
          fi

  # Job 6: Quality gate (runs only on PRs)
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [lint, build, test, security]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Quality gate passed
        run: |
          echo "🎉 All quality checks passed!"
          echo "✅ Linting: Passed"
          echo "✅ Build: Passed" 
          echo "✅ Tests: Passed"
          echo "✅ Coverage: Meets threshold"
          echo "✅ Security: No critical vulnerabilities"
          echo ""
          echo "This pull request is ready for review! 🚀"

  # Job 7: Auto-merge dependabot PRs (optional)
  auto-merge-dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    needs: [lint, build, test, security]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}